USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make

TITLE=enable-mail-bundles
PACKAGE_VERSION=1.0
PACKAGE_NAME=${TITLE}-${PACKAGE_VERSION}
REVERSE_DOMAIN=com.github.tobiasjwm
PAYLOAD=\
	pack-usr-local-outset-login-every-enable-mail-bundles-20170427.sh