USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make

TITLE=PaperCut_LaunchAgent
PACKAGE_NAME=${TITLE}-${PACKAGE_VERSION}
REVERSE_DOMAIN=com.papercut.client.LaunchAgent
PACKAGE_VERSION=1.0
PAYLOAD=\
	pack-Library-LaunchAgents-com.papercut.client.plist