USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make

TITLE=disableSquirrelUpdates
PACKAGE_VERSION=1.1
PACKAGE_NAME=${TITLE}-${PACKAGE_VERSION}
REVERSE_DOMAIN=com.github.tobiasjwm
PAYLOAD=\
	pack-usr-local-outset-login-every-disableSquirrelUpdates-20170501.sh