USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make

TITLE=disableSlackUpdates
PACKAGE_VERSION=2.1
PACKAGE_NAME=${TITLE}-${PACKAGE_VERSION}
REVERSE_DOMAIN=com.rickheil
PAYLOAD=\
	pack-Library-LaunchAgents-com.rickheil.disable-slack-auto-updates.plist