USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make

TITLE=PaperCutClient
PACKAGE_VERSION=16.0
PACKAGE_NAME=${TITLE}-${PACKAGE_VERSION}
REVERSE_DOMAIN=com.papercut.client
PAYLOAD=\
    unbz2-applications-PCClient.app