USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make

TITLE=RansomWhere_Installer
PACKAGE_VERSION=1.2.0
PACKAGE_NAME=${TITLE}-${PACKAGE_VERSION}
REVERSE_DOMAIN=com.objective-see.pkg
PAYLOAD=\
	unbz2-utilities-RansomWhere_Installer.app \
	pack-script-postinstall
