USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make

TITLE=configFinderDefaults
PACKAGE_VERSION=0.1
PACKAGE_NAME=${TITLE}-${PACKAGE_VERSION}
REVERSE_DOMAIN=com.github.tobiasjwm
PAYLOAD=\
	pack-usr-local-outset-login-once-configFinderDefaults.sh