USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make

TITLE=addOffice2016Dock
PACKAGE_NAME=${TITLE}-${PACKAGE_VERSION}
REVERSE_DOMAIN=com.github.tobiasjwm
PACKAGE_VERSION=1.5
PAYLOAD=\
	pack-usr-local-outset-login-once-addOffice2016Dock.sh \
	pack-script-preinstall